fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cpplint
        args: [
            "--filter=-readability/casting,-runtime/threadsafe_fn,-build/include_what_you_use,-runtime/int",
            "--linelength=100",
        ]
